[tool.poetry]
name = "amplfi"
version = "0.0.1"
description = "End-to-end amplfi pipeline components"
authors = [
    "Ethan Marx",
    "Deep Chatterjee"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
jsonargparse = "^4.27.1"
"amplfi.law" = {path = "./amplfi/law", develop = true}
"train" = {path = "./projects/train", develop = true}

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"


[tool.poetry.group.docs.dependencies]
Sphinx = ">5.0"
sphinx-rtd-theme = "^2.0.0"
myst-parser = "^2.0.0"
sphinx-autodoc-typehints = "^2.0.0"
linkify-it-py = "^2.0.3"

[tool.poetry.scripts]
amplfi-init = "scripts.amplfi_init:main"


[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | _build
  | dist
  | docs
)/
'''

[tool.isort]
known_first_party = ["amplfi", "train", "data", "mldatafind"]
known_third_party = ["ml4gw"]
multi_line_output = 3
include_trailing_comma = true
