# lightning.pytorch==2.1.3
seed_everything: 101588
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  logger: null
  max_epochs: 100
  check_val_every_n_epoch: 1
  benchmark: false
model:
  class_path: train.model.PEModel
  init_args:
    arch:
      class_path: train.architectures.flows.CouplingFlow
      init_args:
        hidden_features: 512
        num_transforms: 5
        num_blocks: 2
        context_dim: 128
        embedding_net: 
          class_path: train.architectures.embeddings.ResNet
          init_args: 
            layers: [2, 2]
            norm_groups: 8

    patience: null
    save_top_k_models: 10
data:
  class_path: train.data.sampler.WaveformSamplerDataset
  init_args:
    inference_params: ["phi", "dec", "hrss"]
    data_dir: "/test"
    val_stride: 0.0625 
    kernel_length: 2
    fduration: 1
    psd_length: 10
    highpass: 32
    batches_per_epoch: 200
    batch_size: 1200 
    ifos: ["H1", "L1"] 
    parameter_transformer:
      class_path: train.data.utils.ParameterTransformer
      init_args:
        transforms:
          hrss: torch.log
    device: cpu
    dec: 
      class_path: ml4gw.distributions.Cosine
    psi: 
      class_path: ml4gw.distributions.Uniform
      init_args:
        low: 0
        high: 3.14 
    phi: 
      class_path: ml4gw.distributions.Uniform
      init_args:
        low: -3.14
        high: 3.14
    min_valid_duration: 10000.0
