[tool.pinto]
steps = [
    #"generate_background:generate-background",
    #"generate_waveforms:generate-waveforms",
    #"train:train:coupling"
    "export:export-model:coupling"
]


[tool.typeo.base]
basedir = "${BASE_DIR}"
datadir = "${DATA_DIR}"
logdir = "${BASE_DIR}/log"
sample_rate = 2048
ifos = ['H1', 'L1']
start = 1262607622
stop = 1262620622
test_stop = 1262751694
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
frame_type = "HOFT_C01"
state_flag = "DCS-ANALYSIS_READY_C01:1"
repository_directory = "${BASE_DIR}/model_repo/" 
force_generation = true
kernel_length = 2
highpass = 32
fduration = 1
prior_file = "priors/sine_gaussian.prior"
coupling = {num_flow_steps = 10}
inference_params = ["frequency", "quality", "hrss", "ra", "dec", "psi"]

[tool.typeo.scripts.generate-background]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
start = "${base.start}" 
stop = "${base.stop}" 
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}" 
minimum_length = 10000
force_generation = "${base.force_generation}"

[tool.typeo.scripts.generate-waveforms]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
n_samples = 10000
prior_file = "${base.prior_file}"
sample_rate = "${base.sample_rate}" 
waveform_duration = 8
force_generation = "${base.force_generation}"
waveform = "mlpe.injection.waveforms.sine_gaussian_frequency"

[tool.typeo.scripts.train]
waveform_dataset = "${base.datadir}/signals.h5"
background_path = "${base.datadir}/background.h5" 
logdir = "${base.logdir}"
outdir = "${base.basedir}/training"
inference_params = "${base.inference_params}" 

ifos = "${base.ifos}"

kernel_length = "${base.kernel_length}"
sample_rate = "${base.sample_rate}"
fduration = "${base.fduration}"
highpass = 32 
trigger_distance = -0.5
batch_size = 512
batches_per_epoch = 200
max_epochs = 200

lr = 4e-3
min_lr = 1e-5
decay_steps = 10000
weight_decay = 1e-5
early_stop = 20

device = "cuda"
profile = false
use_amp = false

# arch parameters
commands.coupling = "${base.coupling}"

[tool.typeo.scripts.export-model]
# paths
repository_directory = "${base.repository_directory}" 
outdir = "${base.logdir}"
weights = "${base.basedir}/training/weights.pt"

# input-output mapping info
ifos = "${base.ifos}"
inference_params = "${base.inference_params}" 
kernel_length = "${base.kernel_length}" 
sample_rate = "${base.sample_rate}"
fduration = "${base.fduration}"
highpass = "${base.highpass}"
batch_size = 4 

# repo/triton parameters
platform = "tensorrt_plan"
verbose = false
clean = true

# arch parameters
commands.coupling = "${base.coupling}"
