name: unit-tests
 
on:
  pull_request:
   types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: cicirello/pyaction:4.8
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build and run tests
        run: |
            python -m pip install --upgrade pip∂
            poetry install 
            poetry run pytest -v
        shell: bash
