name: unit-tests
 
on:
  pull_request:
   types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      # container with python and git
      image: cicirello/pyaction:4.32
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: run tests
        run: |
            apt-get update
            apt-get install -y build-essential
            apt-get clean
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install 
            poetry run pytest -v
        shell: bash
